## Project-wide Gradle settings.
APP_VERSION_CODE=1000
APP_VERSION_NAME=1.0.0
APP_PACKAGE=org.nayagram.platform
IS_PRIVATE=false

RELEASE_KEY_PASSWORD=NayaGram@2026#BuildTop
RELEASE_KEY_ALIAS=nayagrampro_key
RELEASE_STORE_PASSWORD=NayaGram@2026#BuildTop

org.gradle.jvmargs=-Xmx6144M -XX:MaxMetaspaceSize=1024m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.enableR8.fullMode=true
android.r8.optimizedResourceShrinking=true
android.enableResourceOptimizations=true
org.gradle.tooling.parallel=true
systemProp.org.gradle.internal.http.socketTimeout=120000
systemProp.org.gradle.internal.http.connectionTimeout=120000
