# NayaGram Official Production Signing Configuration
RELEASE_KEY_PASSWORD=NayaGram@2026#BuildTop
RELEASE_KEY_ALIAS=nayagrampro_key
RELEASE_STORE_PASSWORD=NayaGram@2026#BuildTop
KEYSTORE_FILE=nayagram-release.jks
