# NayaGram Official Production Signing Configuration
RELEASE_KEY_PASSWORD=NayaGram@2026&TGPremik
RELEASE_KEY_ALIAS=payagrampro_key
RELEASE_STORE_PASSWORD=NayaGram@2026&TGPremik
KEYSTORE_FILE=nayagrampro.jks
