# NayaGram Release Signing Configuration
RELEASE_KEY_PASSWORD=Naya%Gram~548K@Pro
RELEASE_KEY_ALIAS=nayagramprokey
RELEASE_STORE_PASSWORD=Naya%Gram~548K@Pro
KEYSTORE_FILE=TMessagesProj/config/release.keystore
