name: Build Release AAB

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Select Flavor"
        required: true
        default: "bundleBundleAfatRelease"
        type: choice
        options:
          - "bundleBundleAfatRelease"
          - "bundleBundleAfat_SDK23Release"

jobs:
  build:
    name: Build Signed Android App Bundle (AAB)
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Setup Android NDK and Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.2.12479018"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.2.12479018" >> $GITHUB_ENV
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_HOME/ndk/27.2.12479018" >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build AAB
        run: ./gradlew :TMessagesProj_App:${{ inputs.flavor }} --no-daemon --stacktrace

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: NayaGram-PlayStore-AAB
          path: TMessagesProj_App/build/outputs/bundle/*/*.aab
          retention-days: 14
